# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Roster',             url: 'Roster'}
- {name: '2022-2023 Schedule', url: 'schedule'}
- {name: 'Highlights',         url: 'highlights'}
- {name: 'Support',            url: 'support'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/pranksters69'}
- {icon: 'facebook', link:   'https://www.facebook.com/MiddleburyPranksters'}
- {icon: 'instagram', link:  'https://www.instagram.com/mgpranksters/?hl=en'}
- {icon: 'envelope', link:   'middultimate@gmail.com'}

# Customize site text

[](assets/img/home.jpg)

Welcome to the Middlebury Pranksters.  Explore our roster, get excited for the season by previewing our schedule, watch highlight videos and more!
  
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

post_date_prefix: 'Written on'
